package com.sheetspace

const val WORKBOOK_SCHEMA_VERSION = 1
const val DEFAULT_COLUMN_COUNT = 10
const val DEFAULT_ROW_COUNT = 20
const val DEFAULT_SHEET_FRAME_WIDTH = 240.0
const val DEFAULT_SHEET_FRAME_HEIGHT = 160.0
