import { cellKey, parseA1Address, parseA1Range, type CellAddress, type CellKey, type CellRange } from '../core/address';
import { cellAddressOf, cellIdentityAt, cellIdentityFromKey, cellIdentityKey } from '../core/cellIdentity';
import type { SheetDocument, SheetFrameProjection, SheetId, SheetTabularProjection, TabularContent, Workbook } from '../core/model';

const a1CellsCache = new WeakMap<TabularContent, Readonly<Record<CellKey, string>>>();
export type ParseResult<T> = { ok: true; value: T } | { ok: false; reason: 'invalid-format' | 'out-of-bounds' | 'unknown-sheet' };
export type NamedCellReference = CellAddress & { sheetName?: string };
export type NamedRangeReference = CellRange & { sheetName?: string };
export function sheetBounds(sheet: SheetDocument | TabularContent) { const content = 'content' in sheet ? sheet.content : sheet; return { rowCount: content.rows.length, columnCount: content.columns.length }; }
export function cellRawContent(sheet: SheetDocument | SheetTabularProjection, address: CellAddress | CellKey): string | undefined { const content = 'content' in sheet ? sheet.content : sheet; const identity = cellIdentityAt(content, address); return identity ? content.cells[cellIdentityKey(identity)] : undefined; }
export function tabularCellsByA1(content: TabularContent): Readonly<Record<CellKey, string>> { const cached = a1CellsCache.get(content); if (cached) return cached; const cells: Record<CellKey, string> = {}; for (const [identityKey, raw] of Object.entries(content.cells)) { const identity = cellIdentityFromKey(identityKey); const address = identity && cellAddressOf(content, identity); if (address) cells[cellKey(address)] = raw; } a1CellsCache.set(content, cells); return cells; }
export function sheetsInOrder(workbook: Workbook): SheetDocument[] { return workbook.manifest.sheetIds.flatMap((id) => workbook.documents[id] ? [workbook.documents[id]] : []); }
export function findSheetById(workbook: Workbook, sheetId: SheetId): SheetDocument | undefined { return workbook.documents[sheetId]; }
export function findSheetByName(workbook: Workbook, sheetName: string): ParseResult<SheetDocument> { const sheet = sheetsInOrder(workbook).find((candidate) => candidate.name === sheetName); return sheet ? { ok: true, value: sheet } : { ok: false, reason: 'unknown-sheet' }; }
export function frameProjection(sheet: SheetDocument): SheetFrameProjection { return { id: sheet.id, name: sheet.name, ...sheet.frame }; }
export function tabularProjection(sheet: SheetDocument): SheetTabularProjection { return { id: sheet.id, name: sheet.name, revision: sheet.revision, ...sheet.content }; }
export function parseNamedA1Address(input: string, workbook: Workbook, defaultSheet?: SheetDocument): ParseResult<NamedCellReference> { const reference = splitSheetReference(input); if (!reference.ok) return reference; const sheet = resolveReferenceSheet(reference.value.sheetName, workbook, defaultSheet); if (!sheet.ok) return sheet; const address = parseA1Address(reference.value.reference, sheetBounds(sheet.value)); return address.ok ? { ok: true, value: { ...address.value, sheetName: reference.value.sheetName } } : address; }
export function parseNamedA1Range(input: string, workbook: Workbook, defaultSheet?: SheetDocument): ParseResult<NamedRangeReference> { const reference = splitSheetReference(input); if (!reference.ok) return reference; const sheet = resolveReferenceSheet(reference.value.sheetName, workbook, defaultSheet); if (!sheet.ok) return sheet; const range = parseA1Range(reference.value.reference, sheetBounds(sheet.value)); return range.ok ? { ok: true, value: { ...range.value, sheetName: reference.value.sheetName } } : range; }
function resolveReferenceSheet(sheetName: string | undefined, workbook: Workbook, defaultSheet?: SheetDocument): ParseResult<SheetDocument> { return !sheetName ? defaultSheet ? { ok: true, value: defaultSheet } : { ok: false, reason: 'unknown-sheet' } : findSheetByName(workbook, sheetName); }
function splitSheetReference(input: string): ParseResult<{ sheetName?: string; reference: string }> { const trimmed = input.trim(); if (trimmed.startsWith("'")) { const closing = trimmed.indexOf("'!"); return closing <= 1 ? { ok: false, reason: 'invalid-format' } : { ok: true, value: { sheetName: trimmed.slice(1, closing), reference: trimmed.slice(closing + 2) } }; } const separator = trimmed.indexOf('!'); return separator === -1 ? { ok: true, value: { reference: trimmed } } : separator === 0 || separator === trimmed.length - 1 ? { ok: false, reason: 'invalid-format' } : { ok: true, value: { sheetName: trimmed.slice(0, separator).trim(), reference: trimmed.slice(separator + 1) } }; }
